// <auto-generated />
using System;
using Academy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.Migrations
{
    [DbContext(typeof(AcademyContext))]
    [Migration("20260913205353_mssql.local_migration_202")]
    partial class mssqllocal_migration_202
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy.Models.Direction", b =>
                {
                    b.Property<byte>("Direction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Direction_id"));

                    b.Property<string>("Direction_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("Academy.Models.Discipline", b =>
                {
                    b.Property<short>("discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("discipline_id"));

                    b.Property<string>("discipline_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("number_of_lessons")
                        .HasColumnType("TINYINT");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Academy.Models.Group", b =>
                {
                    b.Property<int>("Group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Group_id"));

                    b.Property<byte?>("Direction")
                        .HasColumnType("TINYINT");

                    b.Property<string>("Group_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Weekdays")
                        .HasColumnType("TINYINT");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("start_time")
                        .HasColumnType("TIME(0)");

                    b.HasKey("Group_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Academy.Models.Student", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stud_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("IMAGE")
                        .HasColumnName("photo");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("group")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stud_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Academy.Models.Teacher", b =>
                {
                    b.Property<byte>("Teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Teacher_id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("IMAGE")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("SMALLMONEY");

                    b.Property<DateOnly?>("Work_since")
                        .HasColumnType("date");

                    b.HasKey("Teacher_id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
